version: '3.8'

services:
  hall-audit-webhook-bot:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - bot-network

networks:
  bot-network:
    driver: bridge
